DROP TABLE IF EXISTS noteful_notes;
DROP TABLE IF EXISTS noteful_folders;

CREATE TABLE noteful_folders (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  folder_name TEXT NOT NULL
);


CREATE TABLE noteful_notes (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    note_name TEXT NOT NULL,
    modified_date TIMESTAMP NOT NULL DEFAULT now(),
    content TEXT,
    folder_id INTEGER REFERENCES noteful_folders(id) ON DELETE CASCADE
)
